extern CString GetRunDirectory();
extern int FileDelete(CString csFileName);
extern int FileCopy(CString objectFile, CString sourceFile, bool overWrite);
extern int DirectoryCreate(CString dirPath);
extern void SpeedSetting();
extern void MotorStop();
extern void RunLog(CString csMessage);
extern void GetCurDay(CString *csYear, CString *csMonth, CString *csDay);
extern void GetCurTime(CString *csHour, CString *csMin, CString *csSec);
extern int MoveToStart(int nAxis, long lPos);
extern void MoveTo(int nAxis, long lPos);
extern void MotionDataLoad();
extern void FileDelete1(CString csEQNum, CString csFileName);
extern void FileCopy1(CString csFileName,CString csEQTray);
extern void ERLog(CString csMessage);
extern CString GetTime();
extern void PWLoad();
extern void ArrayPosCalc();
extern void CountSave();
extern void CountLoad();
